# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d07749d6297d070e3d42ad7eb1f8f0706cfe11a5a2efd54668f93f294ce802dd504525abfd06bdda2bd9f90443e3df75ae32b06ce13693231d58fb7f456f87d

test:
  secret_key_base: 32ea2d42bfacbe1022f8668660169b9191f86517a5662a08ace051f2cc44db176fc85f45b33c4b6f90e3decf29a8f04a4528f772b87784c1390ed92fda9796c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
